### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by krzyzanowskim**

### CODE REVIEW

**Comment by helje5** [comment]
Awesome fix. Dramatically improved the quality of the compiler.

**Comment by krzyzanowskim** [comment]
☺️

**Comment by helje5** [comment]
Would you be so kind to also provide a unit test for your change? Thanks a lot, we really want to keep the quality prefect!

**Comment by krzyzanowskim** [comment]
sure, due to nature of this change, simply ignore it.

**Comment by helje5** [comment]
That would be unprofessional and we are nothing like that.

**Pull request merged**
